export const paginateTypes={
    SET_PER_PAGE    :"SET_PER_PAGE",
    SET_CURRENT_PAGE:"SET_CURRENT_PAGE",
    TOGGLE_ACTIVE_PAGINATE:"TOGGLE_ACTIVE_PAGINATE",
    TOGGLE_ACTIVE_SCROLL_DATA:"TOGGLE_ACTIVE_SCROLL_DATA",
    SET_SCROLL_LENGTH:"SET_SCROLL_LENGTH"
};
