export const cartActionTypes={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    MOUSE_OUT_HIDDEN:'MOUSE_OUT_HIDDEN',
    MOUSE_IN_HIDDEN:'MOUSE_IN_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    DEC_ITEM:'DEC_ITEM'
};
