export const sliderTypes={
    HOME_SLIDER_COUNT:"HOME_SLIDER_COUNT",
    HOME_AUTOPLAY_SPEED:"HOME_AUTOPLAY_SPEED",
    FREE_COURSE_SLIDER_COUNT:"FREE_COURSE_SLIDER_COUNT",
    FREE_COURSE_AUTOPLAY_SPEED:"FREE_COURSE_AUTOPLAY_SPEED",
    FREE_COURSE_BG_COLOR_FROM:"FREE_COURSE_BG_COLOR_FROM",
    FREE_COURSE_BG_COLOR_TO:"FREE_COURSE_BG_COLOR_TO",
    LAST_COURSES_SLIDER_COUNT:"LAST_COURSES_SLIDER_COUNT",
    LAST_COURSES_AUTOPLAY_SPEED:"LAST_COURSES_AUTOPLAY_SPEED",
    LAST_COURSES_BG_COLOR_FROM:"LAST_COURSES_BG_COLOR_FROM",
    LAST_COURSES_BG_COLOR_TO:"LAST_COURSES_BG_COLOR_TO",
};
