export const coursesType={
    GET_ALL_COURSES_START:"GET_ALL_COURSES_START",
    GET_ALL_COURSES_SUCCESS:"GET_ALL_COURSES_SUCCESS",
    GET_ALL_COURSES_END:"GET_ALL_COURSES_END",
    ADD_COURSE:"ADD_COURSE",
    DELETE_COURSE:"DELETE",
    UPDATE_COURSE:"UPDATE_COURSE"
};
